# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ' '

menu:
- {name: 'Digital Art',  url: 'art'}
- {name: 'Graphics Design', url: 'graphics'}
- {name: 'Photography',      url: 'photogrpahy'}
- {name: 'About',              url: 'about'}
- {name: 'Contact',            url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'facebook', link:   'https://www.facebook.com/profile.php?id=100019360147596'}
- {icon: 'instagram', link:  'https://www.instagram.com/rafiun_haque/'}
- {icon: 'envelope', link:   'mailto:rafiunhaque@gmail.com'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'



post_date_prefix: 'Written on'
